### ISSUE TITLE
Ensure against interface conversion problems

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns-cli#21]
### Description

`panic: interface conversion: interface {} is int, not string` error.

### Steps to Reproduce

1. compile from master
2. attempt to view a CNAME such via commands like the following: `vinyldns record-set --zone-id 89e21e9a-581c-424c-a006-7cb1c4bbcd32 --record-set-id 5862d275-79b8-4689-97ab-4bf16327baeb`

**Expected behavior:** [What you expect to happen]

I expect to view the record set data.

**Actual behavior:** [What actually happens]

```
$ vinyldns record-set --zone-id 89e21e9a-581c-424c-a006-7cb1c4bbcd32 --record-set-id 5862d275-79b8-4689-97ab-4bf16327baeb
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
main.getRecordValue(...)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vinyldns.go:745
main.getRecord(0xc420012900, 0x1, 0x4, 0x7ffeefbff1cb, 0x24)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vinyldns.go:721 +0x19b2
main.recordSet(0xc4200cc840, 0x100, 0xc4200cc840)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vinyldns.go:590 +0x19e
github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli.HandleAction(0x131eea0, 0x13a6da8, 0xc4200cc840, 0xc420010400, 0x0)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli.Command.Run(0x1391d87, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13a0f67, 0x3b, 0x0, ...)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli.(*App).Run(0xc42009a9c0, 0xc4200100c0, 0x6, 0x6, 0x0, 0x0)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli/app.go:255 +0x6a0
github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli.(*App).RunAndExitOnError(0xc42009a9c0)
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vendor/github.com/urfave/cli/app.go:276 +0x53
main.main()
        /Users/mball0001/dev/go/src/github.com/vinyldns/vinyldns-cli/vinyldns.go:284 +0x19d6
```

### Versions

Only `master` at this time; no releases.

**Comment by mdb** [comment]
I believe this was introduced via PR #19
